sudo: required

services:
  - docker

script:
  - docker build -t promact/dotnet-core-lambda-docker .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push promact/dotnet-core-lambda-docker